tap "homebrew/bundle"
brew "bat"
brew "eza"
brew "git"
brew "httpie"
brew "mas"
brew "openjdk@17"
brew "python@3.11"
brew "python-tk@3.11"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "alfred"
cask "anki"
cask "camtasia"
cask "discord"
cask "dropbox"
cask "elgato-camera-hub"
cask "firefox"
cask "gitkraken"
cask "google-chrome"
cask "google-earth-pro"
cask "ithoughtsx"
cask "jetbrains-toolbox"
cask "logi-options+"
cask "mathpix-snipping-tool"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "notion"
cask "notion-calendar"
cask "obsidian"
cask "pdf-expert"
cask "proton-mail"
cask "snagit"
cask "trader-workstation"
cask "tradingview"
cask "visual-studio-code"
cask "vmware-fusion"
cask "wacom-tablet"
cask "zoom"
cask "zotero"
mas "1Password for Safari", id: 1569813296
mas "24 Hour Wallpaper", id: 1226087575
mas "Final Cut Pro", id: 424389933
mas "Kindle", id: 302584613
mas "Microsoft To Do", id: 1274495053
mas "MindNode", id: 1289197285
mas "MindNode Next", id: 6446116532
mas "Notability", id: 360593530
mas "Remote Desktop", id: 409907375
mas "Rosetta Stone", id: 1476088902
mas "TextSniper", id: 1528890965
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "pedro-bronsveld.anki-editor"
vscode "redhat.java"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
